services:
  server:
    container_name: cs-api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
      - NEON_URL=${NEON_URL}
      - SKINS_CDN_URL=${SKINS_CDN_URL}
