services:
  csupgrade-api:
    container_name: csupgrade-api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - GOFLAGS=-buildvcs=false
    depends_on:
      - db
      - valkey

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: erob
      POSTGRES_DB: csupgrade
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"

volumes:
  pgdata: {}
