# fly.toml app configuration file generated for csupgrade-go-api on 2025-05-06T18:15:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'csupgrade-go-api'
kill_signal = "SIGINT"
kill_timeout = 15
primary_region = 'atl'

[build]
  dockerfile = './Dockerfile'
  build-target = 'prod'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
